# Generated by Django 4.2.11 on 2024-11-04 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_atualizacaoestoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='tipo_movimentacao',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='usuario_responsavel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_venda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade_medida',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='produtos/imagens/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
